In [ ]:
"""
BROWNLEE, Jason. Basics of Linear Algebra for Machine Learning: Discover
the Mathematical Language of Data in Python. 2ª ed. 
MachineLearningMastery.com: 2021.

página: 125
"""
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
"""
Exemplo do livro:
ANTON, Howard; RORRES, Chris. Álgebra Linear com Aplicações. 10ª Edição. Porto Alegre: Bookman, 2012.

página: 296
"""
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[3, 0],
[8, -1]])
print(A)
# factorize
values, vectors = eig(A)
print(values)

print(vectors)

[[ 3  0]
 [ 8 -1]]
[-1.  3.]
[[0.         0.4472136 ]
 [1.         0.89442719]]


In [ ]:
"""
Exemplo do livro:
ANTON, Howard; RORRES, Chris. Álgebra Linear com Aplicações. 10ª Edição. Porto Alegre: Bookman, 2012.

página: 296
"""
#teste dos autovalores e autovetores
import numpy as np
from numpy import array

A = array([
[3, 0],
[8, -1]])

#Autovetor [1, 2] para o autovalor 3
x = array([1, 2])
B = A.dot(x)
norma1 = np.linalg.norm(x)
norma2 = np.linalg.norm(x*3)
print (B)
print("Comprimento do vetor [1,2]: ", norma1)
print("Comprimento do vetor [3,6]: ", norma2)
print()

#Autovetor [5, 10] para o autovalor 3
x = array([5, 10])
B = A.dot(x)
norma1 = np.linalg.norm(x)
norma2 = np.linalg.norm(x*3)
print (B)
print("Comprimento do vetor [5, 10]: ", norma1)
print("Comprimento do vetor [15, 30]: ", norma2)
print()

#Autovetor [0.4472136, 0.89442719] para o autovalor 3
x = array([0.4472136, 0.89442719])
B = A.dot(x)
norma1 = np.linalg.norm(x)
norma2 = np.linalg.norm(x*3)
print (B)
print("Comprimento do vetor [0.4472136, 0.89442719]: ", norma1)
print("Comprimento do vetor [1.3416408, 2,68328157]: ", norma2)
print()

#Autovetor [0, 5] para o autovalor -1
x = array([0, 5])
B = A.dot(x)
norma1 = np.linalg.norm(x)
norma2 = np.linalg.norm(-x)
print (B)
print("Comprimento do vetor [0,5]: ", norma1)
print("Comprimento do vetor [0,-5]: ", norma2)



[3 6]
Comprimento do vetor [1,2]:  2.23606797749979
Comprimento do vetor [3,6]:  6.708203932499369

[15 30]
Comprimento do vetor [5, 10]:  11.180339887498949
Comprimento do vetor [15, 30]:  33.54101966249684

[1.3416408  2.68328161]
Comprimento do vetor [0.4472136, 0.89442719]:  1.000000001118128
Comprimento do vetor [1.3416408, 2,68328157]:  3.0000000033543843

[ 0 -5]
Comprimento do vetor [0,5]:  5.0
Comprimento do vetor [0,-5]:  5.0


In [1]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[6, 7],
[1, 0]])
print(A)
# factorize
values, vectors = eig(A)
print(values)

print(vectors)

[[6 7]
 [1 0]]
[ 7. -1.]
[[ 0.98994949 -0.70710678]
 [ 0.14142136  0.70710678]]
