In [ ]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [2]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[0, 1, 5],
[3, -6, 9],
[2, 6, 1]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 0  1  5]
 [ 3 -6  9]
 [ 2  6  1]]
165.00000000000009


In [ ]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[3, 4, 1],
[0, 2/3, 17/3],
[0, 0, 207/3]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 3.          4.          1.        ]
 [ 0.          0.66666667  5.66666667]
 [ 0.          0.         69.        ]]
138.00000000000006


In [3]:
# matrix determinant A
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 0, 2],
[-3, 4, 6],
[-1, -2, 3]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 1  0  2]
 [-3  4  6]
 [-1 -2  3]]
44.000000000000014


In [4]:
# matrix determinant A1
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[6, 0, 2],
[30, 4, 6],
[8, -2, 3]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 6  0  2]
 [30  4  6]
 [ 8 -2  3]]
-40.0


In [5]:
# matrix determinant A2
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 6, 2],
[-3, 30, 6],
[-1, 8, 3]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 1  6  2]
 [-3 30  6]
 [-1  8  3]]
72.0


In [6]:
# matrix determinant A3
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 0, 6],
[-3, 4, 30],
[-1, -2, 8]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[ 1  0  6]
 [-3  4 30]
 [-1 -2  8]]
152.0
