In [1]:
"""
No Exercícios 11, encontre a distância euclidiana entre u e v. 

11. 
(a) u = (3, 3, 3), v = (1, 0, 4)  
(b) u = (0, -2, -1, 1), v = (-3, 2, 4, 4)  
(c) u = (3, -3, -2, 0, -3, 13, 5),  v = (-4, 1, -1, 5, 0, -11, 4)  

ANTON, Howard; RORRES, Chris. Álgebra Linear com Aplicações. 10ª Edição. Porto Alegre: Bookman, 2012, p. 142.

"""
import numpy as np

vecA = np.array((3, 3, 3))
vecB = np.array((1, 0, 4))

dist = np.linalg.norm(vecA - vecB)
print(vecA)
print(vecB)
print("Distância euclidiana:" , dist)
print()

vecC = np.array((0, -2, -1, 1))
vecD = np.array((-3, 2, 4, 4))

dist = np.linalg.norm(vecC - vecD)
print(vecC)
print(vecD)
print("Distância euclidiana:" , dist)
print()

vecE = np.array((3, -3, -2, 0, -3, 13, 5))
vecF = np.array((-4, 1, -1, 5, 0, -11, 4))

dist = np.linalg.norm(vecA - vecB)
print(vecE)
print(vecF)
print("Distância euclidiana:" , dist)

[3 3 3]
[1 0 4]
Distância euclidiana: 3.7416573867739413

[ 0 -2 -1  1]
[-3  2  4  4]
Distância euclidiana: 7.681145747868608

[ 3 -3 -2  0 -3 13  5]
[ -4   1  -1   5   0 -11   4]
Distância euclidiana: 3.7416573867739413
