In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[0.0, -5.0, 4.0],
[0.0, 3.0, 6.0],
[1.0, 5.0, 1.0]])
print(A)
print()
# invert matrix
B = inv(A)
print(B)
print()
# multiply A and B
# alternative syntax in Python 3.5: I = A @ B
I = A.dot(B)
print(I)

[[ 0. -5.  4.]
 [ 0.  3.  6.]
 [ 1.  5.  1.]]

[[ 0.64285714 -0.5952381   1.        ]
 [-0.14285714  0.0952381  -0.        ]
 [ 0.07142857  0.11904762  0.        ]]

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 8.32667268e-17  1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17 -2.77555756e-17  1.00000000e+00]]


In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0, 3.0],
[0.0, 1.0, 4.0],
[5.0, 6.0, 0.0]])
print(A)
print()
# invert matrix
B = inv(A)
print(B)
print()
# multiply A and B
# alternative syntax in Python 3.5: I = A @ B
I = A.dot(B)
print(I)

[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

[[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]


In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[3.0, 2.0, -1.0],
[1.0, 6.0, 3.0],
[2.0, -4.0, 0.0]])
print(A)
print()
# invert matrix
B = array([
[12/64, 4/64, 12/64],
[6/64, 2/64, -10/64],
[-16/64, 16/64, 16/64]])
print(B)
print()
# multiply A and B
# alternative syntax in Python 3.5: I = A @ B
I = A.dot(B)
print(I)

[[ 3.  2. -1.]
 [ 1.  6.  3.]
 [ 2. -4.  0.]]

[[ 0.1875   0.0625   0.1875 ]
 [ 0.09375  0.03125 -0.15625]
 [-0.25     0.25     0.25   ]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[3.0, 2.0, -1.0],
[1.0, 6.0, 3.0],
[2.0, -4.0, 0.0]])
print(A)
print()
# invert matrix
B = array([
[3/16, 1/16, 3/16],
[3/32, 1/32, -5/32],
[-1/4, 1/4, 1/4]])
print(B)
print()
# multiply A and B
# alternative syntax in Python 3.5: I = A @ B
I = A.dot(B)
print(I)

[[ 3.  2. -1.]
 [ 1.  6.  3.]
 [ 2. -4.  0.]]

[[ 0.1875   0.0625   0.1875 ]
 [ 0.09375  0.03125 -0.15625]
 [-0.25     0.25     0.25   ]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[3.0, 4.0],
[1.0, 4.0]])
print(A)
print()
# invert matrix
B = array([
[1/2, -1/2],
[-1/8, 3/8]])
print(B)
print()
# multiply A and B
# alternative syntax in Python 3.5: I = A @ B
I = A.dot(B)
print(I)

[[3. 4.]
 [1. 4.]]

[[ 0.5   -0.5  ]
 [-0.125  0.375]]

[[1. 0.]
 [0. 1.]]
