In [ ]:
"""
Norma de um vetor
"""
import numpy as np

vecA = np.array((3, 4))
vecB = np.array((7, 3, 4))
vecC = np.array((21, 9, 12))
vecD = np.array((3, -3, -2, 0, -3, 13, 5))

normaA = np.linalg.norm(vecA)
normaB = np.linalg.norm(vecB)
normaC = np.linalg.norm(vecC)
normaD = np.linalg.norm(vecD)

print(vecA)
print("Norma: " , normaA)
print()
print(vecB)
print("Norma: " , normaB)
print()
print(vecC)
print("Norma: " , normaC)
print()
print(vecD)
print("Norma: " , normaD)

[3 4]
Norma:  5.0

[1 4 4 4]
Norma:  7.0

[21  9 12]
Norma:  25.80697580112788

[ 3 -3 -2  0 -3 13  5]
Norma:  15.0


In [ ]:
import numpy as np 
v = np.array((3, 4, 0))
u = np.array((1.5, -2, 2))
print(np.dot(u, v))

-3.5


In [ ]:
"""
Cálculo do ângulo

"""
import numpy as np
import math

v = np.array((3, 4, 0))
u = np.array((1.5, -2, 2))

normaA = np.linalg.norm(u)
normaB = np.linalg.norm(v)


print(u)
print("Norma u: " , normaA)
print()
print(v)
print("Norma: " , normaB)
print()

uv = np.dot(u, v)

angulorad = math.degrees(np.arccos(np.linalg.norm(uv) / (normaA * normaB)))

print("Norma uv: ", uv)
print("Ângulo: ", angulorad, " graus")

[ 1.5 -2.   2. ]
Norma u:  3.2015621187164243

[3 4 0]
Norma:  5.0

Norma uv:  -3.5
Ângulo:  77.37064198561451  graus


In [ ]:
"""
Cálculo do ângulo

"""
import numpy as np
import math

v = np.array((0, 0, 1))
u = np.array((0, 2, 2))

normaA = np.linalg.norm(u)
normaB = np.linalg.norm(v)


print(u)
print("Norma u: " , normaA)
print()
print(v)
print("Norma: " , normaB)
print()

uv = np.dot(u, v)

angulorad = math.degrees(np.arccos(np.linalg.norm(uv) / (normaA * normaB)))

print("Norma uv: ", uv)
print("Ângulo: ", angulorad, " graus")

[0 2 2]
Norma u:  2.8284271247461903

[0 0 1]
Norma:  1.0

Norma uv:  2
Ângulo:  45.00000000000001  graus
