In [3]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[-1, 2, 7, 0],
[3, 5, -8, 4],
[1, 2, 7, -3],
[4, -2, 1, 0]])
print(A)
# calculate transpose
C = A.T
print()
print(C)

[[-1  2  7  0]
 [ 3  5 -8  4]
 [ 1  2  7 -3]
 [ 4 -2  1  0]]

[[-1  3  1  4]
 [ 2  5  2 -2]
 [ 7 -8  7  1]
 [ 0  4 -3  0]]
